import { Product } from './types';

export const FRUIT_PRODUCTS: Product[] = [
  {
    id: 'm1',
    nameEn: 'Rajshahi Himsagar Mango',
    nameBn: 'রাজশাহী হিমসাগর আম',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1553279768-865429fa0078?q=80&w=600&auto=format&fit=crop',
    originalPrice: 160,
    discountPrice: 125,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.8,
    reviewCount: 142,
    stockLeft: 45,
    totalStock: 120,
    isFlashSale: true,
    descriptionEn: 'Famed for its rich aroma, smooth pulp and honey-like sweetness, direct from the orchards of Rajshahi.',
    descriptionBn: 'রাজশাহীর বাগান থেকে সরাসরি সংগৃহীত, চমৎকার সুবাস ও মিষ্টি স্বাদের জন্য বিখ্যাত হিমসাগর আম।',
    benefitsEn: ['Rich in Vitamin A and C', 'Boosts immune system', 'Supports healthy digestion'],
    benefitsBn: ['প্রচুর ভিটামিন এ এবং সি সমৃদ্ধ', 'রোগ প্রতিরোধ ক্ষমতা বাড়ায়', 'হজম প্রক্রিয়া সচল রাখে']
  },
  {
    id: 'm2',
    nameEn: 'Premium Gala Apple (Imported)',
    nameBn: 'প্রিমিয়াম গালা আপেল',
    category: 'imported',
    image: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?q=80&w=600&auto=format&fit=crop',
    originalPrice: 280,
    discountPrice: 220,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.7,
    reviewCount: 98,
    stockLeft: 18,
    totalStock: 60,
    isFlashSale: true,
    descriptionEn: 'Crisp, sweet, and highly nutritious. Freshly imported crunchy apples sourced from certified global orchards.',
    descriptionBn: 'মুচমুচে, মিষ্টি এবং অত্যন্ত পুষ্টিকর। বিশ্বখ্যাত বাগান থেকে আমদানিকৃত তাজা লাল আপেল।',
    benefitsEn: ['High dietary fiber', 'Good for heart health', 'Rich in antioxidants'],
    benefitsBn: ['প্রচুর আঁশ যুক্ত', 'হার্টের স্বাস্থ্যের জন্য ভালো', 'অ্যান্টিঅক্সিডেন্ট সমৃদ্ধ']
  },
  {
    id: 'm3',
    nameEn: 'Dinajpur China-3 Litchi',
    nameBn: 'দিনাজপুর চায়না-৩ লিচু',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?q=80&w=600&auto=format&fit=crop',
    originalPrice: 450,
    discountPrice: 380,
    unitEn: '100 pcs',
    unitBn: '১০০ পিস',
    rating: 4.9,
    reviewCount: 185,
    stockLeft: 22,
    totalStock: 50,
    isFlashSale: true,
    descriptionEn: 'The pride of Dinajpur. Extra juicy, sweet, thick flesh and exceptionally small seeds.',
    descriptionBn: 'দিনাজপুরের সেরা লিচু। ছোট বীজ ও অতিরিক্ত মিষ্টি ও রসালো শাঁসযুক্ত চায়না-৩ লিচু।',
    benefitsEn: ['Rehydrates body instantly', 'High in Vitamin C', 'Improves skin health'],
    benefitsBn: ['শরীরকে দ্রুত আর্দ্র করে', 'ভিটামিন সি এর চমৎকার উৎস', 'ত্বক উজ্জ্বল রাখতে সাহায্য করে']
  },
  {
    id: 'm4',
    nameEn: 'Sweet Seedless Green Grapes',
    nameBn: 'মিষ্টি বীজহীন সবুজ আঙুর',
    category: 'citrus',
    image: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?q=80&w=600&auto=format&fit=crop',
    originalPrice: 320,
    discountPrice: 260,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.6,
    reviewCount: 84,
    stockLeft: 30,
    totalStock: 80,
    isFlashSale: false,
    descriptionEn: 'Naturally sweet, seedless premium grapes that offer a juicy punch in every single bite.',
    descriptionBn: 'প্রাকৃতিকভাবে মিষ্টি এবং বীজহীন প্রিমিয়াম আঙুর, প্রতি কামড়েই পাবেন চমৎকার সতেজতা।',
    benefitsEn: ['Boosts energy instantly', 'Supports brain health', 'Helps blood circulation'],
    benefitsBn: ['সহজেই এনার্জি প্রদান করে', 'মস্তিষ্কের সচলতা বাড়ায়', 'রক্ত সঞ্চালন উন্নত করে']
  },
  {
    id: 'm5',
    nameEn: 'Srimangal Honey Queen Pineapple',
    nameBn: 'শ্রীমঙ্গল মধু রানী আনারস',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1550258987-190a2d41a8ba?q=80&w=600&auto=format&fit=crop',
    originalPrice: 60,
    discountPrice: 45,
    unitEn: 'piece',
    unitBn: 'পিস',
    rating: 4.5,
    reviewCount: 63,
    stockLeft: 12,
    totalStock: 40,
    isFlashSale: true,
    descriptionEn: 'Grown in the hilly tea-capital of Srimangal, super sweet and aromatic miniature queen pineapples.',
    descriptionBn: 'শ্রীমঙ্গলের পাহাড়ি অঞ্চলের অসাধারণ মিষ্টি ও সুগন্ধি মধু রানী আনারস।',
    benefitsEn: ['Aids digestion effectively', 'Rich in Bromelain enzyme', 'Reduces cold symptoms'],
    benefitsBn: ['হজম শক্তি বাড়াতে অত্যন্ত কার্যকরী', 'ব্রোমেলেইন এনজাইম সমৃদ্ধ', 'ঠান্ডা ও সর্দির উপশম করে']
  },
  {
    id: 'm6',
    nameEn: 'Sweet Mandarin Orange',
    nameBn: 'মিষ্টি চায়না ম্যান্ডারিন কমলা',
    category: 'citrus',
    image: 'https://images.unsplash.com/photo-1611080626919-7cf5a9dbab5b?q=80&w=600&auto=format&fit=crop',
    originalPrice: 250,
    discountPrice: 195,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.8,
    reviewCount: 112,
    stockLeft: 55,
    totalStock: 150,
    isFlashSale: false,
    descriptionEn: 'Easy to peel, seed-free, sweet and bursting with fresh imported citrus juice.',
    descriptionBn: 'সহজে খোসা ছাড়ানো যায়, অত্যন্ত মিষ্টি এবং ভিটামিন-সি ভরপুর আমদানিকৃত তাজা কমলা।',
    benefitsEn: ['Excellent source of Vitamin C', 'Keeps skin hydrated', 'Combats flu viruses'],
    benefitsBn: ['ভিটামিন সি এর অসাধারণ উৎস', 'ত্বক সজীব ও আর্দ্র রাখে', 'ফ্লু ও ভাইরাল জ্বর প্রতিরোধ করে']
  },
  {
    id: 'm7',
    nameEn: 'Ruby Red Pomegranate (Anar)',
    nameBn: 'রুবি লাল বেদানা/আনার',
    category: 'imported',
    image: 'https://images.unsplash.com/photo-1627485264983-76eff4d320b9?q=80&w=600&auto=format&fit=crop',
    originalPrice: 420,
    discountPrice: 350,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.9,
    reviewCount: 139,
    stockLeft: 8,
    totalStock: 30,
    isFlashSale: true,
    descriptionEn: 'Deep crimson pearls filled with sweet juice. Sourced fresh for nutritional optimization.',
    descriptionBn: 'রক্তের মতো লাল দানাযুক্ত মিষ্টি স্বাদের প্রিমিয়াম ডালিম বা আনার। অত্যন্ত পুষ্টিকর।',
    benefitsEn: ['Increases blood hemoglobin', 'High in iron and zinc', 'Protects cellular health'],
    benefitsBn: ['শরীরে হিমোগ্লোবিন বাড়ায়', 'প্রচুর আয়রন ও জিংক সমৃদ্ধ', 'কোষের ক্ষয় রোধ করে']
  },
  {
    id: 'm8',
    nameEn: 'Narsingdi Sagar Banana',
    nameBn: 'নরসিংদীর সুস্বাদু সাগর কলা',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?q=80&w=600&auto=format&fit=crop',
    originalPrice: 120,
    discountPrice: 95,
    unitEn: 'dozen',
    unitBn: 'ডজন',
    rating: 4.6,
    reviewCount: 76,
    stockLeft: 40,
    totalStock: 100,
    isFlashSale: false,
    descriptionEn: 'Authentic Sagar Kola from Narsingdi gardens, rich in potassium, naturally ripened without chemicals.',
    descriptionBn: 'রাসায়নিক মুক্ত উপায়ে পাকানো, নরসিংদীর খাঁটি ও সুস্বাদু পুষ্টিকর সাগর কলা। ',
    benefitsEn: ['Massive potassium source', 'Perfect for post-workout energy', 'Regulates blood pressure'],
    benefitsBn: ['প্রচুর পটাশিয়াম সমৃদ্ধ', 'ব্যায়ামের পর শক্তি জোগাতে এক নম্বর', 'রক্তচাপ নিয়ন্ত্রণে সাহায্য করে']
  },
  {
    id: 'm9',
    nameEn: 'Sweet Crimson Watermelon',
    nameBn: 'মিষ্টি লাল তরমুজ (রসালো)',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=600&auto=format&fit=crop',
    originalPrice: 300,
    discountPrice: 240,
    unitEn: 'piece',
    unitBn: 'পিস',
    rating: 4.7,
    reviewCount: 104,
    stockLeft: 15,
    totalStock: 50,
    isFlashSale: false,
    descriptionEn: 'Premium sweet watermelons with beautiful red flesh. The perfect hydration companion.',
    descriptionBn: 'ভেতরে টকটকে লাল এবং অত্যন্ত মিষ্টি রসালো তরমুজ। গরমের স্বস্তির জন্য শ্রেষ্ঠ উপহার।',
    benefitsEn: ['Contains 92% refreshing water', 'Great anti-inflammatory benefits', 'Replenishes electrolytes'],
    benefitsBn: ['৯২% পানি সমৃদ্ধ', 'শরীর ঠাণ্ডা রাখে ও প্রদাহ কমায়', 'ইলেক্ট্রোলাইটের ঘাটতি পূরণ করে']
  },
  {
    id: 'm10',
    nameEn: 'Fresh Green Coconut (Daab)',
    nameBn: 'কচি ডাব (প্রকৃতির স্যালাইন)',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1525385133336-254847240d92?q=80&w=600&auto=format&fit=crop',
    originalPrice: 130,
    discountPrice: 99,
    unitEn: 'piece',
    unitBn: 'পিস',
    rating: 4.9,
    reviewCount: 156,
    stockLeft: 28,
    totalStock: 80,
    isFlashSale: true,
    descriptionEn: 'Direct from coastal gardens, packed with natural essential mineral waters and sweet soft kernel.',
    descriptionBn: 'উপকূলীয় অঞ্চলের বাগান থেকে আনা, তাজা ডাবের পানি ও নরম সুস্বাদু শাঁস যুক্ত।',
    benefitsEn: ['Balances body electrolytes', 'Naturally lowers acidity', 'Excellent low-cal drink'],
    benefitsBn: ['শরীরের প্রাকৃতিক স্যালাইন', 'অ্যাসিডিটি ও বুক জ্বলা কমায়', 'চর্বিমুক্ত একটি স্বাস্থ্যকর পানীয়']
  },
  {
    id: 'm11',
    nameEn: 'Sweet Pink Dragon Fruit',
    nameBn: 'মিষ্টি গোলাপি ড্রাগন ফল',
    category: 'berries',
    image: 'https://images.unsplash.com/photo-1506806732259-39c2d0268443?q=80&w=600&auto=format&fit=crop',
    originalPrice: 380,
    discountPrice: 299,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.5,
    reviewCount: 48,
    stockLeft: 20,
    totalStock: 50,
    isFlashSale: false,
    descriptionEn: 'Vibrant pink skin and sweet red-purple flesh. Locally cultivated premium dragon fruit.',
    descriptionBn: 'আকর্ষণীয় গোলাপি রঙের মিষ্টি ড্রাগন ফল। দেশেই অর্গানিক উপায়ে চাষকৃত।',
    benefitsEn: ['Packed with prebiotics', 'Excellent for immunity', 'Highly nutritious'],
    benefitsBn: ['প্রিবায়োটিক সমৃদ্ধ', 'রোগ প্রতিরোধ ক্ষমতা চমৎকার বাড়ায়', 'কম ক্যালোরি এবং পুষ্টিকর']
  },
  {
    id: 'm12',
    nameEn: 'Organic Thai Guava (Peyara)',
    nameBn: 'মিষ্টি থাই পেয়ারা (ভিটামিন-সি)',
    category: 'local',
    image: 'https://images.unsplash.com/photo-1626245914619-a9a7a9cb5bf9?q=80&w=600&auto=format&fit=crop',
    originalPrice: 80,
    discountPrice: 59,
    unitEn: 'kg',
    unitBn: 'কেজি',
    rating: 4.7,
    reviewCount: 79,
    stockLeft: 35,
    totalStock: 100,
    isFlashSale: false,
    descriptionEn: 'Crisp, firm, and white inside. Absolutely organic, sweet Guava rich in life-saving Vitamin C.',
    descriptionBn: 'মুচমুচে এবং মিষ্টি থাই পেয়ারা। ভিটামিন সি তে ভরপুর একটি দারুণ দেশীয় ফল।',
    benefitsEn: ['Has 4x more Vit C than oranges', 'Improves eyesight', 'Regulates blood sugar'],
    benefitsBn: ['কমলার চেয়ে ৪ গুণ বেশি ভিটামিন সি যুক্ত', 'চোখের চারপাশের জ্যোতি বাড়ায়', 'ডায়াবেটিস নিয়ন্ত্রণে উপকারী']
  }
];

export const CUSTOMER_REVIEWS = [
  {
    id: 1,
    name: 'আরাফাত রহমান',
    rating: 5,
    date: '২০২৬-০৫-২০',
    comment: 'পলাশবাড়ী ফ্রুট শপ থেকে হিমসাগর আম নিয়েছিলাম। আমগুলো আসলেই অসাধারণ ও মিষ্টি ছিল। কোনো ফরমালিনের গন্ধ নেই। সার্ভিস খুব দ্রুত!',
    fruit: 'রাজশাহী হিমসাগর আম'
  },
  {
    id: 2,
    name: 'তাসনোভা ইসলাম',
    rating: 5,
    date: '২০২৬-০৫-১৮',
    comment: 'Very premium fruit quality! Apples and Green Grapes are so fresh and crunchy. Highly recommended!',
    fruit: 'প্রিমিয়াম গালা আপেল'
  },
  {
    id: 3,
    name: 'এমডি ইয়াসিন',
    rating: 4,
    date: '২০২৬-০৫-১৫',
    comment: 'লিচুগুলো অর্ডার করার ৩ ঘণ্টার মধ্যে ডেলিভারি পেয়েছি। একদম সতেজ ছিল। দারুণ সেবা। ফোন নাম্বারে যোগাযোগ করেও সহজে পাওয়া যায়।',
    fruit: 'দিনাজপুর চায়না-৩ লিচু'
  }
];
